# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /usr/src/cplusplus

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /usr/src/cplusplus

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /usr/src/cplusplus/CMakeFiles /usr/src/cplusplus//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /usr/src/cplusplus/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cplusplus

# Build rule for target.
cplusplus: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cplusplus
.PHONY : cplusplus

# fast build rule for target.
cplusplus/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplusplus.dir/build.make CMakeFiles/cplusplus.dir/build
.PHONY : cplusplus/fast

constants/http/Http.o: constants/http/Http.cpp.o
.PHONY : constants/http/Http.o

# target to build an object file
constants/http/Http.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplusplus.dir/build.make CMakeFiles/cplusplus.dir/constants/http/Http.cpp.o
.PHONY : constants/http/Http.cpp.o

constants/http/Http.i: constants/http/Http.cpp.i
.PHONY : constants/http/Http.i

# target to preprocess a source file
constants/http/Http.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplusplus.dir/build.make CMakeFiles/cplusplus.dir/constants/http/Http.cpp.i
.PHONY : constants/http/Http.cpp.i

constants/http/Http.s: constants/http/Http.cpp.s
.PHONY : constants/http/Http.s

# target to generate assembly for a file
constants/http/Http.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplusplus.dir/build.make CMakeFiles/cplusplus.dir/constants/http/Http.cpp.s
.PHONY : constants/http/Http.cpp.s

constants/http/methods/Methods.o: constants/http/methods/Methods.cpp.o
.PHONY : constants/http/methods/Methods.o

# target to build an object file
constants/http/methods/Methods.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplusplus.dir/build.make CMakeFiles/cplusplus.dir/constants/http/methods/Methods.cpp.o
.PHONY : constants/http/methods/Methods.cpp.o

constants/http/methods/Methods.i: constants/http/methods/Methods.cpp.i
.PHONY : constants/http/methods/Methods.i

# target to preprocess a source file
constants/http/methods/Methods.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplusplus.dir/build.make CMakeFiles/cplusplus.dir/constants/http/methods/Methods.cpp.i
.PHONY : constants/http/methods/Methods.cpp.i

constants/http/methods/Methods.s: constants/http/methods/Methods.cpp.s
.PHONY : constants/http/methods/Methods.s

# target to generate assembly for a file
constants/http/methods/Methods.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplusplus.dir/build.make CMakeFiles/cplusplus.dir/constants/http/methods/Methods.cpp.s
.PHONY : constants/http/methods/Methods.cpp.s

constants/http/responseCodes/ResponseCodes.o: constants/http/responseCodes/ResponseCodes.cpp.o
.PHONY : constants/http/responseCodes/ResponseCodes.o

# target to build an object file
constants/http/responseCodes/ResponseCodes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplusplus.dir/build.make CMakeFiles/cplusplus.dir/constants/http/responseCodes/ResponseCodes.cpp.o
.PHONY : constants/http/responseCodes/ResponseCodes.cpp.o

constants/http/responseCodes/ResponseCodes.i: constants/http/responseCodes/ResponseCodes.cpp.i
.PHONY : constants/http/responseCodes/ResponseCodes.i

# target to preprocess a source file
constants/http/responseCodes/ResponseCodes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplusplus.dir/build.make CMakeFiles/cplusplus.dir/constants/http/responseCodes/ResponseCodes.cpp.i
.PHONY : constants/http/responseCodes/ResponseCodes.cpp.i

constants/http/responseCodes/ResponseCodes.s: constants/http/responseCodes/ResponseCodes.cpp.s
.PHONY : constants/http/responseCodes/ResponseCodes.s

# target to generate assembly for a file
constants/http/responseCodes/ResponseCodes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplusplus.dir/build.make CMakeFiles/cplusplus.dir/constants/http/responseCodes/ResponseCodes.cpp.s
.PHONY : constants/http/responseCodes/ResponseCodes.cpp.s

constants/routes/Routes.o: constants/routes/Routes.cpp.o
.PHONY : constants/routes/Routes.o

# target to build an object file
constants/routes/Routes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplusplus.dir/build.make CMakeFiles/cplusplus.dir/constants/routes/Routes.cpp.o
.PHONY : constants/routes/Routes.cpp.o

constants/routes/Routes.i: constants/routes/Routes.cpp.i
.PHONY : constants/routes/Routes.i

# target to preprocess a source file
constants/routes/Routes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplusplus.dir/build.make CMakeFiles/cplusplus.dir/constants/routes/Routes.cpp.i
.PHONY : constants/routes/Routes.cpp.i

constants/routes/Routes.s: constants/routes/Routes.cpp.s
.PHONY : constants/routes/Routes.s

# target to generate assembly for a file
constants/routes/Routes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplusplus.dir/build.make CMakeFiles/cplusplus.dir/constants/routes/Routes.cpp.s
.PHONY : constants/routes/Routes.cpp.s

database/DBConnection.o: database/DBConnection.cpp.o
.PHONY : database/DBConnection.o

# target to build an object file
database/DBConnection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplusplus.dir/build.make CMakeFiles/cplusplus.dir/database/DBConnection.cpp.o
.PHONY : database/DBConnection.cpp.o

database/DBConnection.i: database/DBConnection.cpp.i
.PHONY : database/DBConnection.i

# target to preprocess a source file
database/DBConnection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplusplus.dir/build.make CMakeFiles/cplusplus.dir/database/DBConnection.cpp.i
.PHONY : database/DBConnection.cpp.i

database/DBConnection.s: database/DBConnection.cpp.s
.PHONY : database/DBConnection.s

# target to generate assembly for a file
database/DBConnection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplusplus.dir/build.make CMakeFiles/cplusplus.dir/database/DBConnection.cpp.s
.PHONY : database/DBConnection.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplusplus.dir/build.make CMakeFiles/cplusplus.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplusplus.dir/build.make CMakeFiles/cplusplus.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplusplus.dir/build.make CMakeFiles/cplusplus.dir/main.cpp.s
.PHONY : main.cpp.s

models/Auth/Auth.o: models/Auth/Auth.cpp.o
.PHONY : models/Auth/Auth.o

# target to build an object file
models/Auth/Auth.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplusplus.dir/build.make CMakeFiles/cplusplus.dir/models/Auth/Auth.cpp.o
.PHONY : models/Auth/Auth.cpp.o

models/Auth/Auth.i: models/Auth/Auth.cpp.i
.PHONY : models/Auth/Auth.i

# target to preprocess a source file
models/Auth/Auth.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplusplus.dir/build.make CMakeFiles/cplusplus.dir/models/Auth/Auth.cpp.i
.PHONY : models/Auth/Auth.cpp.i

models/Auth/Auth.s: models/Auth/Auth.cpp.s
.PHONY : models/Auth/Auth.s

# target to generate assembly for a file
models/Auth/Auth.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplusplus.dir/build.make CMakeFiles/cplusplus.dir/models/Auth/Auth.cpp.s
.PHONY : models/Auth/Auth.cpp.s

models/User/User.o: models/User/User.cpp.o
.PHONY : models/User/User.o

# target to build an object file
models/User/User.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplusplus.dir/build.make CMakeFiles/cplusplus.dir/models/User/User.cpp.o
.PHONY : models/User/User.cpp.o

models/User/User.i: models/User/User.cpp.i
.PHONY : models/User/User.i

# target to preprocess a source file
models/User/User.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplusplus.dir/build.make CMakeFiles/cplusplus.dir/models/User/User.cpp.i
.PHONY : models/User/User.cpp.i

models/User/User.s: models/User/User.cpp.s
.PHONY : models/User/User.s

# target to generate assembly for a file
models/User/User.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplusplus.dir/build.make CMakeFiles/cplusplus.dir/models/User/User.cpp.s
.PHONY : models/User/User.cpp.s

server/Server.o: server/Server.cpp.o
.PHONY : server/Server.o

# target to build an object file
server/Server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplusplus.dir/build.make CMakeFiles/cplusplus.dir/server/Server.cpp.o
.PHONY : server/Server.cpp.o

server/Server.i: server/Server.cpp.i
.PHONY : server/Server.i

# target to preprocess a source file
server/Server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplusplus.dir/build.make CMakeFiles/cplusplus.dir/server/Server.cpp.i
.PHONY : server/Server.cpp.i

server/Server.s: server/Server.cpp.s
.PHONY : server/Server.s

# target to generate assembly for a file
server/Server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplusplus.dir/build.make CMakeFiles/cplusplus.dir/server/Server.cpp.s
.PHONY : server/Server.cpp.s

server/router/Router.o: server/router/Router.cpp.o
.PHONY : server/router/Router.o

# target to build an object file
server/router/Router.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplusplus.dir/build.make CMakeFiles/cplusplus.dir/server/router/Router.cpp.o
.PHONY : server/router/Router.cpp.o

server/router/Router.i: server/router/Router.cpp.i
.PHONY : server/router/Router.i

# target to preprocess a source file
server/router/Router.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplusplus.dir/build.make CMakeFiles/cplusplus.dir/server/router/Router.cpp.i
.PHONY : server/router/Router.cpp.i

server/router/Router.s: server/router/Router.cpp.s
.PHONY : server/router/Router.s

# target to generate assembly for a file
server/router/Router.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplusplus.dir/build.make CMakeFiles/cplusplus.dir/server/router/Router.cpp.s
.PHONY : server/router/Router.cpp.s

topics/pointers/Pointer.o: topics/pointers/Pointer.cpp.o
.PHONY : topics/pointers/Pointer.o

# target to build an object file
topics/pointers/Pointer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplusplus.dir/build.make CMakeFiles/cplusplus.dir/topics/pointers/Pointer.cpp.o
.PHONY : topics/pointers/Pointer.cpp.o

topics/pointers/Pointer.i: topics/pointers/Pointer.cpp.i
.PHONY : topics/pointers/Pointer.i

# target to preprocess a source file
topics/pointers/Pointer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplusplus.dir/build.make CMakeFiles/cplusplus.dir/topics/pointers/Pointer.cpp.i
.PHONY : topics/pointers/Pointer.cpp.i

topics/pointers/Pointer.s: topics/pointers/Pointer.cpp.s
.PHONY : topics/pointers/Pointer.s

# target to generate assembly for a file
topics/pointers/Pointer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cplusplus.dir/build.make CMakeFiles/cplusplus.dir/topics/pointers/Pointer.cpp.s
.PHONY : topics/pointers/Pointer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cplusplus"
	@echo "... constants/http/Http.o"
	@echo "... constants/http/Http.i"
	@echo "... constants/http/Http.s"
	@echo "... constants/http/methods/Methods.o"
	@echo "... constants/http/methods/Methods.i"
	@echo "... constants/http/methods/Methods.s"
	@echo "... constants/http/responseCodes/ResponseCodes.o"
	@echo "... constants/http/responseCodes/ResponseCodes.i"
	@echo "... constants/http/responseCodes/ResponseCodes.s"
	@echo "... constants/routes/Routes.o"
	@echo "... constants/routes/Routes.i"
	@echo "... constants/routes/Routes.s"
	@echo "... database/DBConnection.o"
	@echo "... database/DBConnection.i"
	@echo "... database/DBConnection.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... models/Auth/Auth.o"
	@echo "... models/Auth/Auth.i"
	@echo "... models/Auth/Auth.s"
	@echo "... models/User/User.o"
	@echo "... models/User/User.i"
	@echo "... models/User/User.s"
	@echo "... server/Server.o"
	@echo "... server/Server.i"
	@echo "... server/Server.s"
	@echo "... server/router/Router.o"
	@echo "... server/router/Router.i"
	@echo "... server/router/Router.s"
	@echo "... topics/pointers/Pointer.o"
	@echo "... topics/pointers/Pointer.i"
	@echo "... topics/pointers/Pointer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

